### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by univiest** [rwthmoodle/moodle-mod_pdfannotator#111]
Hello.
Apparently the statistics in pdf annotation are not available. There is an error in the statistics tab:
![pdfstatistics](https://github.com/user-attachments/assets/17bcdc75-637b-4703-a831-5292068939d6)

version v1.5.5, but also older versions

**Comment by caiadogithub** [comment]
Same problem here... Using Postgres 16, Moodle 4.1

![Firefox_Screenshot_2024-12-15T22-59-42 286Z](https://github.com/user-attachments/assets/84f52e51-9ca3-4b62-8252-58fbcaa824e8)

**Comment by caiadogithub** [comment]
Hi, Amrita1991,

Just to let you know the "**PDF Annotator v1.5 release 7 (2024121200)**" did not solved issue #111

Using Postgres 16, Moodle 4.5

Ricardo

**Comment by Amrita1991** [comment]
user reported that this issue is solved

**Comment by caiadogithub** [comment]
Issue [#111](https://github.com/rwthmoodle/moodle-mod_pdfannotator/issues/111) is not solved!

**Comment by univietw** [comment]
Issue #111 was solved yesterday with the hotfix. What I dislike though is that the old tag was deleted and a new one created with the same name. I was very confused and looked at it for at least an hour until I realized that I have a different version than in github, even though my tag name was the same.
You shouldn't do this as it's confusing everyone which version they have. Versions should be unique. Tags should not be changed. That's what branches are for.

**Comment by Amrita1991** [comment]
Sorry for the inconvenience. We will improve our practises next time
